<?php
ob_start();

// if (session_status() === PHP_SESSION_NONE) {
//     session_start();
// }

// if (!isset($_SESSION['admin_id'])) {
//     die("Access denied. Please login first.");
// }

// if (!isset($_SESSION['download_token'])) {
//     die("Download token not found. Refresh the page and try again.");
// }

// $downloadToken = $_SESSION['download_token'];
// if (!isset($_GET['token']) || $_GET['token'] !== $downloadToken) {
//     die("Invalid download token. Please refresh the page and try again.");
// }

// // --- REGENERATE TOKEN after successful check ---
// $_SESSION['download_token'] = bin2hex(random_bytes(16));
// $downloadToken = $_SESSION['download_token'];

require('fpdf186/fpdf.php');
require_once __DIR__ . '/../../backend/db_script/db.php';
require_once __DIR__ . '/../../backend/db_script/appData.php';

$appData = new AppData($pdo);

// === Filters (if applicable) ===
$fromDate = $_GET['fromDate'] ?? null;
$toDate = $_GET['toDate'] ?? null;

// === Fetch Analytics Data from Backend ===
$analyticsData = $appData->getBusinessAnalyticsSummary($fromDate, $toDate);
/*
Expected backend structure example:
[
  'metrics' => [
      'Total Sales' => '₱1,250,000',
      'Total Orders' => '482',
      'Avg Order Value' => '₱2,590',
      'Revenue Growth' => '+18.5%',
      'Top Product' => 'Premium Coffee Beans',
      'Top Customer' => 'Maria Santos'
  ],
  'graphs' => [
      'sales_trend' => 'graphs/sales_trend.png',
      'revenue_breakdown' => 'graphs/revenue_breakdown.png',
      'customer_growth' => 'graphs/customer_growth.png',
      'customer_sentiment' => 'graphs/customer_sentiment.png'
  ],
  'summary' => "Overall, business performance continues to grow with strong customer engagement and consistent sales momentum..."
]
*/


// ================= PDF CLASS ===================
class ReportPDF extends FPDF {
    var $headerFill = [210, 180, 140];
    var $subHeaderFill = [188, 143, 143];
    var $dataFillAlt = [255, 248, 220];
    var $dataFill = [255, 255, 255];
    var $borderColor = [139, 69, 19];
    var $textDark = [101, 67, 33];

    var $leftMargin = 15;
    var $rightMargin = 15;
    var $topMargin = 8;
    var $bottomMargin = 20;

    // === Header ===
    function Header() {
        if (file_exists('../public/assests/leilife.png')) {
            $this->Image('../public/assests/leilife.png', 15, 10, 22);
        }

        $this->SetFont('Arial', 'B', 16);
        $this->SetTextColor($this->textDark[0], $this->textDark[1], $this->textDark[2]);
        $this->Cell(0, 8, 'Leilife Cafe & Resto', 0, 1, 'C');

        $this->SetFont('Arial', '', 11);
        $this->SetTextColor(110, 80, 45);
        $this->Cell(0, 6, 'Lunduyan Langaray, Brgy. 14 Caloocan City', 0, 1, 'C');

        $this->Ln(4);
        $this->SetLineWidth(0.8);
        $this->SetDrawColor($this->borderColor[0], $this->borderColor[1], $this->borderColor[2]);
        $this->Line(15, $this->GetY(), 195, $this->GetY());
        $this->Ln(10);
    }

    // === Footer ===
    function Footer() {
        $this->SetY(-15);
        $this->SetFont('Arial', 'I', 9);
        $this->SetTextColor(120, 80, 40);
        $this->Cell(0, 10, 'Generated by Leilife | ' . date('F d, Y') . ' | Page ' . $this->PageNo(), 0, 0, 'C');
    }

    // === Section Header ===
    function SectionHeader($label) {
        $this->SetFillColor($this->subHeaderFill[0], $this->subHeaderFill[1], $this->subHeaderFill[2]);
        $this->SetTextColor(255, 255, 255);
        $this->SetFont('Arial', 'B', 13);
        $this->Cell(0, 9, "  " . strtoupper($label), 0, 1, 'L', true);
        $this->Ln(4);
    }

    // === Metrics Table ===
    function MetricTable($metrics) {
        $this->SetDrawColor($this->borderColor[0], $this->borderColor[1], $this->borderColor[2]);
        $this->SetFont('Arial', '', 11);
        $this->SetTextColor($this->textDark[0], $this->textDark[1], $this->textDark[2]);

        $colWidth = 90;
        $colHeight = 11;
        $counter = 0;

        foreach ($metrics as $label => $value) {
            if ($counter % 2 == 0)
                $this->SetFillColor($this->dataFillAlt[0], $this->dataFillAlt[1], $this->dataFillAlt[2]);
            else
                $this->SetFillColor($this->dataFill[0], $this->dataFill[1], $this->dataFill[2]);

            $this->SetFont('Arial', 'B', 11);
            $this->Cell(45, $colHeight, $label, 1, 0, 'C', true);
            $this->SetFont('Arial', '', 11);
            $this->Cell(45, $colHeight, $value, 1, 0, 'C');

            $counter++;
            if ($counter % 2 == 0) $this->Ln();
        }

        if ($counter % 2 != 0) $this->Ln();
        $this->Ln(8);
    }

    // === Two-column Graph Section ===
    function TwoColumnGraphSection($leftLabel, $leftImage, $rightLabel, $rightImage) {
        $this->SetFont('Arial', 'B', 12);
        $this->SetFillColor($this->headerFill[0], $this->headerFill[1], $this->headerFill[2]);
        $this->SetTextColor(60, 40, 20);

        $this->Cell(90, 8, "  " . $leftLabel, 0, 0, 'L', true);
        $this->Cell(10);
        $this->Cell(90, 8, "  " . $rightLabel, 0, 1, 'L', true);

        $y = $this->GetY();
        if (file_exists($leftImage)) $this->Image($leftImage, 20, $y + 5, 80, 55);
        if (file_exists($rightImage)) $this->Image($rightImage, 115, $y + 5, 80, 55);
        $this->Ln(65);
    }

    // === Executive Summary ===
    function SummarySection($summary) {
        $this->SectionHeader('Executive Summary');
        $this->SetFont('Arial', '', 11);
        $this->SetTextColor($this->textDark[0], $this->textDark[1], $this->textDark[2]);
        $this->MultiCell(0, 7, $summary, 0, 'J');
        $this->Ln(8);
    }
}


// ================== GENERATE PDF ==================
$pdf = new ReportPDF();
$pdf->AddPage();

// === SECTION 1: Metrics ===
$pdf->SectionHeader('Overall Metrics');
$metrics = $analyticsData['metrics'] ?? [
    'Total Sales' => '₱0',
    'Total Orders' => '0',
    'Avg Order Value' => '₱0',
    'Revenue Growth' => '0%',
    'Top Product' => 'N/A',
    'Top Customer' => 'N/A'
];
$pdf->MetricTable($metrics);

// === SECTION 2: Charts ===
$pdf->SectionHeader('Performance Charts');
$graphs = $analyticsData['graphs'] ?? [];

$pdf->TwoColumnGraphSection(
    'Sales Trend',
    $graphs['sales_trend'] ?? 'graphs/sales_trend.png',
    'Revenue Breakdown',
    $graphs['revenue_breakdown'] ?? 'graphs/revenue_breakdown.png'
);

$pdf->TwoColumnGraphSection(
    'Customer Growth',
    $graphs['customer_growth'] ?? 'graphs/customer_growth.png',
    'Customer Sentiment Summary',
    $graphs['customer_sentiment'] ?? 'graphs/customer_sentiment.png'
);

// === SECTION 3: Executive Summary ===
$pdf->SummarySection($analyticsData['summary'] ?? 'No summary data available.');

ob_end_clean();
$pdf->Output('I', 'Ageless_Business_Report.pdf');
exit;
?>
